/* Application bootstrap. Loaded before router.js, after every view script.
   Each page (/, /warzones/, /map/, ...) is a real subpage shipping this same
   shell with every panel already in the DOM (see index.html) — only one is
   shown at a time. <body data-tab="..."> names the view the page shows on
   first load. router.js intercepts nav clicks after that and calls runTab()
   directly instead of letting the browser navigate, so tab switches never
   reload the page; a real navigation (JS disabled, crawler, direct link)
   still lands on the matching static subpage generated by
   tools/build_pages.py. */
"use strict";

const App = (() => {
  /* Order defines the rail and the bottom nav. `path` must match a key in
     ROUTES so soft navigation and the static subpages agree. */
  const TABS = {
    overview:  { view: OverviewView,  panel: "panel-overview",  path: "/",              icon: "◈" },
    warzones:  { view: WarzonesView,  panel: "panel-warzones",  path: "/warzones/",     icon: "▤" },
    map:       { view: MapView,       panel: "panel-map",       path: "/map/",          icon: "◇" },
    history:   { view: HistoryView,   panel: "panel-history",   path: "/history/",      icon: "◠" },
    lp:        { view: LpStoreView,   panel: "panel-lp",        path: "/lp/",           icon: "≡" },
    boards:    { view: BoardsView,    panel: "panel-boards",    path: "/leaderboards/", icon: "▲" },
    campaigns: { view: CampaignsView, panel: "panel-campaigns", path: "/campaigns/",    icon: "✶" },
    faq:       { view: FaqView,       panel: "panel-faq",       path: "/faq/",          icon: "?" }
  };

  /* Matches the --tbl/--card swap in css/app.css. Views ask this instead of
     rendering both a table and a card list into the DOM and hiding one. */
  const NARROW = window.matchMedia("(max-width: 900px)");

  let activeTab = "overview";
  const loaded = new Set();
  /* Separate from `loaded`, which the refresh button deliberately deletes
     from to force a reload — everLoaded never shrinks, so a force refresh
     never re-triggers the skeleton over an already-visible table. */
  const everLoaded = new Set();
  let autoTimer = null;
  let currentTheme = "dark";

  const $ = (id) => document.getElementById(id);
  const isNarrow = () => NARROW.matches;

  function updateLiveChip(on) {
    $("live-chip").classList.toggle("paused", !on);
    $("live-label").textContent = on ? t("live_label") : t("paused_label");
    $("auto-refresh").classList.toggle("active", on);
  }

  /* Rail and bottom nav render from the same TABS order; real <a href> so
     middle-click, "open in new tab" and crawlers all still work. */
  function renderNav() {
    const links = (extra) => Object.entries(TABS).map(([id, tab]) => `
      <a href="${tab.path}" id="${extra}-tab-${id}" class="${id === activeTab ? "active" : ""}" title="${esc(t("tab_" + id))}">
        <span class="rail-icon">${tab.icon}</span>
        <span class="rail-label">${esc(t("tab_" + id))}</span>
      </a>`).join("");

    $("rail").innerHTML = links("rail") +
      `<div class="rail-foot">${esc(t("updated_label"))}<br><span id="rail-updated"></span></div>`;
    $("bottom-nav").innerHTML = links("bot");
  }

  function setUpdated(text) {
    const el = $("rail-updated");
    if (el) el.textContent = text;
  }

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      $("rail-tab-" + id)?.classList.toggle("active", id === tabId);
      $("bot-tab-" + id)?.classList.toggle("active", id === tabId);
    }
    $("page-title").textContent = t("pt_" + tabId);
    $("page-sub").textContent = t("ps_" + tabId);
    /* Each view owns the chip row; anything left from the previous tab goes. */
    $("page-chips").innerHTML = "";
  }

  function setStatus(state, message = "") {
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  /* Central error sink so async view actions never die silently in the console. */
  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + " — " + hint);
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    setStatus("idle"); // clear any error left over from a previous tab
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    if (!everLoaded.has(tabId)) tab.view.skeleton?.();
    setStatus("loading");
    try {
      await tab.view.load();
      loaded.add(tabId);
      everLoaded.add(tabId);
      /* Set before render() so a view with a better answer (a mirror's own
         fetch timestamp, say) can still overwrite it. */
      setUpdated(new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC");
      tab.view.render();
      setStatus("idle");
    } catch (err) {
      reportError(err);
    }
  }

  /* The header strip summarises both warzones on every tab, so it is fed by
     whichever view last loaded occupancy rather than by the overview alone. */
  function renderFrontStrip(rows) {
    if (!rows || !rows.length) { $("front-strip").innerHTML = ""; return; }
    $("front-strip").innerHTML = rows.map(r => `
      <div class="strip-cell">
        <span class="strip-tag">${esc(r.tag)}</span>
        <span class="strip-val" style="color:${r.aColor}">${r.a}</span>
        <span class="strip-bar"><span style="width:${r.pct};background:${r.aColor}"></span></span>
        <span class="strip-val" style="color:${r.bColor}">${r.b}</span>
      </div>`).join("");
  }

  function rerenderAll() {
    applyI18n();
    renderNav();
    $("page-title").textContent = t("pt_" + activeTab);
    $("page-sub").textContent = t("ps_" + activeTab);
    $("theme-toggle").textContent = currentTheme === "dark" ? t("theme_to_light") : t("theme_to_dark");
    updateLiveChip(!!autoTimer);
    for (const tabId of loaded) TABS[tabId].view.render();
  }

  /* Button label names what clicking switches *to*, not the current state. */
  function setTheme(theme) {
    currentTheme = theme;
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("tow_theme", theme);
    $("theme-toggle").textContent = theme === "dark" ? t("theme_to_light") : t("theme_to_dark");
  }

  function setAutoRefresh(on) {
    localStorage.setItem("tow_auto_refresh", on ? "1" : "0");
    updateLiveChip(on);
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    /* Turning auto-refresh on also refetches straight away — the header has
       no separate manual refresh in this layout, so this is the way to force
       fresh data on demand. */
    $("auto-refresh").addEventListener("click", () => {
      const on = !autoTimer;
      setAutoRefresh(on);
      if (on) { loaded.delete(activeTab); runTab(activeTab, true); }
    });
    setAutoRefresh(localStorage.getItem("tow_auto_refresh") === "1");

    $("lang-toggle").addEventListener("click", () => {
      LANG = LANG === "de" ? "en" : "de";
      localStorage.setItem("tow_lang", LANG);
      rerenderAll();
    });

    $("theme-toggle").addEventListener("click", () => {
      setTheme(document.documentElement.dataset.theme === "light" ? "dark" : "light");
    });
    setTheme(localStorage.getItem("tow_theme") || "dark");

    /* Crossing the table/card breakpoint changes what the views emit, so the
       loaded ones have to be asked for their other layout. */
    NARROW.addEventListener("change", () => {
      for (const tabId of loaded) TABS[tabId].view.render();
    });

    const pageTab = document.body.dataset.tab;
    activeTab = TABS[pageTab] ? pageTab : "overview";
    applyI18n();
    renderNav();
    runTab(activeTab);
  }

  return { init, runTab, reportError, isNarrow, renderFrontStrip, setUpdated, TABS };
})();

document.addEventListener("DOMContentLoaded", App.init);
