/* Application bootstrap. Loaded last.
   Each page (/, /map/, /lp/, ...) is a real subpage sharing this shell;
   <body data-tab="..."> names the view the page shows. Navigation between
   tabs is plain links, generated by tools/build_pages.py. */
"use strict";

const App = (() => {
  const TABS = {
    warzones:  { view: WarzonesView,  panel: "panel-warzones" },
    map:       { view: MapView,       panel: "panel-map" },
    history:   { view: HistoryView,   panel: "panel-history" },
    lp:        { view: LpStoreView,   panel: "panel-lp" },
    jobs:      { view: JobsView,      panel: "panel-jobs" },
    boards:    { view: BoardsView,    panel: "panel-boards" },
    campaigns: { view: CampaignsView, panel: "panel-campaigns" },
    faq:       { view: FaqView,       panel: "panel-faq" }
  };

  let activeTab = "warzones";
  const loaded = new Set();
  let autoTimer = null;

  const $ = (id) => document.getElementById(id);

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      $("tab-" + id).classList.toggle("active", id === tabId);
    }
  }

  function setStatus(state, message = "") {
    $("loading").classList.toggle("hidden", state !== "loading");
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  /* Central error sink so async view actions never die silently in the console. */
  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + " — " + hint);
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    setStatus("loading");
    try {
      await tab.view.load();
      loaded.add(tabId);
      tab.view.render();
      $("timestamp").textContent =
        t("ts_label") + " " + new Date().toLocaleTimeString(LANG === "de" ? "de-DE" : "en-US");
      setStatus("idle");
    } catch (err) {
      reportError(err);
    }
  }

  function rerenderAll() {
    applyI18n();
    for (const tabId of loaded) TABS[tabId].view.render();
  }

  function setAutoRefresh(on) {
    localStorage.setItem("tow_auto_refresh", on ? "1" : "0");
    $("auto-refresh").classList.toggle("active-mode", on);
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    $("refresh").addEventListener("click", () => {
      loaded.delete(activeTab);
      runTab(activeTab, true);
    });
    $("auto-refresh").addEventListener("click", () => {
      setAutoRefresh(!autoTimer);
    });
    setAutoRefresh(localStorage.getItem("tow_auto_refresh") === "1");
    $("lang-de").addEventListener("click", () => { LANG = "de"; rerenderAll(); });
    $("lang-en").addEventListener("click", () => { LANG = "en"; rerenderAll(); });
    $("jobs-more").addEventListener("click", () => JobsView.loadMore());

    applyI18n();
    const pageTab = document.body.dataset.tab;
    runTab(TABS[pageTab] ? pageTab : "warzones");
  }

  return { init, runTab, reportError };
})();

document.addEventListener("DOMContentLoaded", App.init);
