/* Application bootstrap. Loaded before router.js, after every view script.
   Each page (/, /map/, /lp/, ...) is a real subpage shipping this same shell
   with every panel already in the DOM (see index.html) — only one is shown
   at a time. <body data-tab="..."> names the view the page shows on first
   load. router.js intercepts nav clicks after that and calls runTab()
   directly instead of letting the browser navigate, so tab switches never
   reload the page; a real navigation (JS disabled, crawler, direct link)
   still lands on the matching static subpage generated by
   tools/build_pages.py. */
"use strict";

const App = (() => {
  const TABS = {
    warzones:  { view: WarzonesView,  panel: "panel-warzones" },
    map:       { view: MapView,       panel: "panel-map" },
    history:   { view: HistoryView,   panel: "panel-history" },
    lp:        { view: LpStoreView,   panel: "panel-lp" },
    boards:    { view: BoardsView,    panel: "panel-boards" },
    campaigns: { view: CampaignsView, panel: "panel-campaigns" },
    faq:       { view: FaqView,       panel: "panel-faq" }
  };

  let activeTab = "warzones";
  const loaded = new Set();
  let autoTimer = null;
  let lastRefresh = null;
  let currentTheme = "dark";

  const $ = (id) => document.getElementById(id);

  function renderTimestamp() {
    if (lastRefresh) $("timestamp").textContent = t("ts_label") + " " + fmtTime(lastRefresh, {}, true);
  }

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      $("tab-" + id).classList.toggle("active", id === tabId);
    }
  }

  function setStatus(state, message = "") {
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  /* Central error sink so async view actions never die silently in the console. */
  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + " — " + hint);
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    setStatus("idle"); // clear any error left over from a previous tab
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    setStatus("loading");
    try {
      await tab.view.load();
      loaded.add(tabId);
      tab.view.render();
      lastRefresh = new Date();
      renderTimestamp();
      setStatus("idle");
    } catch (err) {
      reportError(err);
    }
  }

  function rerenderAll() {
    applyI18n();
    $("theme-toggle").textContent = currentTheme === "dark" ? t("theme_light") : t("theme_dark");
    renderTimestamp();
    for (const tabId of loaded) TABS[tabId].view.render();
  }

  /* Button label names what clicking switches *to*, not the current state —
     "Light mode" while dark is active, "Dark mode" once light is active. */
  function setTheme(theme) {
    currentTheme = theme;
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("tow_theme", theme);
    $("theme-toggle").textContent = theme === "dark" ? t("theme_light") : t("theme_dark");
  }

  function setAutoRefresh(on) {
    localStorage.setItem("tow_auto_refresh", on ? "1" : "0");
    $("auto-refresh").classList.toggle("active-mode", on);
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    $("refresh").addEventListener("click", () => {
      loaded.delete(activeTab);
      runTab(activeTab, true);
    });
    $("auto-refresh").addEventListener("click", () => {
      setAutoRefresh(!autoTimer);
    });
    setAutoRefresh(localStorage.getItem("tow_auto_refresh") === "1");
    $("lang-de").addEventListener("click", () => { LANG = "de"; rerenderAll(); });
    $("lang-en").addEventListener("click", () => { LANG = "en"; rerenderAll(); });

    $("theme-toggle").addEventListener("click", () => {
      setTheme(document.documentElement.dataset.theme === "light" ? "dark" : "light");
    });
    setTheme(localStorage.getItem("tow_theme") || "dark");

    applyI18n();
    const pageTab = document.body.dataset.tab;
    runTab(TABS[pageTab] ? pageTab : "warzones");
  }

  return { init, runTab, reportError };
})();

document.addEventListener("DOMContentLoaded", App.init);
