/* Generated from tools/build_pages.py's PAGES list — do not edit by hand.
   Route table for js/router.js (soft navigation between tabs). */
"use strict";

const ROUTES = {
  "/": {lang: "en", tab: "overview", title: "Warzone Companion \u2014 EVE Online Factional Warfare", description: "Factional Warfare companion for EVE Online: both warzones at a glance, live maps, frontline roles, LP store optimizer, leaderboards and Military Campaigns.", canonical: "https://warzone.tonicdock.com/", alt: "/de/"},
  "/warzones/": {lang: "en", tab: "warzones", title: "Warzones \u2014 Warzone Companion", description: "Every contested EVE Online Factional Warfare system with its occupier, frontline role, victory points, Advantage and kills in the last hour.", canonical: "https://warzone.tonicdock.com/warzones/", alt: "/de/warzones/"},
  "/map/": {lang: "en", tab: "map", title: "Warzone Map \u2014 Warzone Companion", description: "Interactive EVE Online Factional Warfare warzone maps: occupancy, frontline status, Advantage, insurgencies and activity per system.", canonical: "https://warzone.tonicdock.com/map/", alt: "/de/map/"},
  "/history/": {lang: "en", tab: "history", title: "Warzone History \u2014 Warzone Companion", description: "EVE Online Factional Warfare over time: systems held, pilots, LP value per militia and a full system flip log.", canonical: "https://warzone.tonicdock.com/history/", alt: "/de/history/"},
  "/lp/": {lang: "en", tab: "lp", title: "LP Store Optimizer \u2014 Warzone Companion", description: "ISK per LP for all EVE Online militia LP stores, with live Jita order-book prices and market depth.", canonical: "https://warzone.tonicdock.com/lp/", alt: "/de/lp/"},
  "/leaderboards/": {lang: "en", tab: "boards", title: "Leaderboards \u2014 Warzone Companion", description: "EVE Online Factional Warfare leaderboards: top characters and corporations by kills and victory points.", canonical: "https://warzone.tonicdock.com/leaderboards/", alt: "/de/leaderboards/"},
  "/campaigns/": {lang: "en", tab: "campaigns", title: "Military Campaigns \u2014 Warzone Companion", description: "EVE Online Military Campaigns with live progress, participation, official titles, objectives and rewards.", canonical: "https://warzone.tonicdock.com/campaigns/", alt: "/de/campaigns/"},
  "/faq/": {lang: "en", tab: "faq", title: "FAQ \u2014 Warzone Companion", description: "How the Warzone Companion works: data sources, frontline rules, Advantage, insurgencies and the flip feed.", canonical: "https://warzone.tonicdock.com/faq/", alt: "/de/faq/"},
  "/de/": {lang: "de", tab: "overview", title: "Warzone Companion \u2014 Fraktionskrieg (Factional Warfare) in EVE Online", description: "Fraktionskrieg in EVE Online: beide Warzones auf einen Blick, Live-Karten, Frontlinien, LP-Store-Rechner, Ranglisten und Military Campaigns.", canonical: "https://warzone.tonicdock.com/de/", alt: "/"},
  "/de/warzones/": {lang: "de", tab: "warzones", title: "Warzones \u2014 Warzone Companion", description: "Jedes umk\u00e4mpfte System im Fraktionskrieg von EVE Online mit Besatzer, Frontlinien-Rolle, Siegpunkten, Advantage und Kills der letzten Stunde.", canonical: "https://warzone.tonicdock.com/de/warzones/", alt: "/warzones/"},
  "/de/map/": {lang: "de", tab: "map", title: "Karte der Warzones \u2014 Warzone Companion", description: "Interaktive Karten der Warzones im Fraktionskrieg von EVE Online: Besatzung, Frontlinie, Advantage, Insurgencies und Aktivit\u00e4t je System.", canonical: "https://warzone.tonicdock.com/de/map/", alt: "/map/"},
  "/de/history/": {lang: "de", tab: "history", title: "Verlauf \u2014 Warzone Companion", description: "Der Fraktionskrieg in EVE Online \u00fcber die Zeit: gehaltene Systeme, Piloten, LP-Wert je Miliz und ein vollst\u00e4ndiges Wechsel-Protokoll.", canonical: "https://warzone.tonicdock.com/de/history/", alt: "/history/"},
  "/de/lp/": {lang: "de", tab: "lp", title: "LP-Store-Rechner \u2014 Warzone Companion", description: "ISK pro LP f\u00fcr alle Milizen-LP-Stores in EVE Online, mit Live-Preisen aus dem Jita-Orderbuch und Markttiefe.", canonical: "https://warzone.tonicdock.com/de/lp/", alt: "/lp/"},
  "/de/leaderboards/": {lang: "de", tab: "boards", title: "Ranglisten \u2014 Warzone Companion", description: "Ranglisten im Fraktionskrieg von EVE Online: die besten Charaktere und Corporations nach Kills und Siegpunkten.", canonical: "https://warzone.tonicdock.com/de/leaderboards/", alt: "/leaderboards/"},
  "/de/campaigns/": {lang: "de", tab: "campaigns", title: "Kampagnen (Military Campaigns) \u2014 Warzone Companion", description: "Military Campaigns in EVE Online mit Live-Fortschritt, Beteiligung, offiziellen Titeln, Zielen und Belohnungen.", canonical: "https://warzone.tonicdock.com/de/campaigns/", alt: "/campaigns/"},
  "/de/faq/": {lang: "de", tab: "faq", title: "H\u00e4ufige Fragen \u2014 Warzone Companion", description: "Wie der Warzone Companion arbeitet: Datenquellen, Frontlinien-Regeln, Advantage, Insurgencies und der Wechsel-Feed.", canonical: "https://warzone.tonicdock.com/de/faq/", alt: "/faq/"}
};
